In [34]:
# ============================================================
# Arithmetic Operations
# ============================================================

import numpy as np
np.random.seed(0)
A = np.random.randint(1, 10, (5, 5))
B = np.random.randint(1,10, (5,5))
print(A)
print(B)
print(f'Sum of A: {A.sum()}')
print(f'Sum of A along axis 0: {A.sum(axis=0)}')
print(f'Sum of A along axis 1: {A.sum(axis=1)}')
print(f'div int {A//2}')
print(f'A+B={A+B}')
print(f'A-B={A-B}')
print(f'Minimum of A: {A.min()}')
print(f'Maximum of A: {A.max()}')
print(f'Minimum of A along axis 0: {A.min(axis=0)}')
print(f'Maximum of A along axis 1: {A.max(axis=1)}')
print(f'Exponential of A: {np.exp(A)}')
print(f'Square root of A: {np.sqrt(A)}')
print(f'Square of A: {np.square(A)}')


[[6 1 4 4 8]
 [4 6 3 5 8]
 [7 9 9 2 7]
 [8 8 9 2 6]
 [9 5 4 1 4]]
[[6 1 3 4 9]
 [2 4 4 4 8]
 [1 2 1 5 8]
 [4 3 8 3 1]
 [1 5 6 6 7]]
Sum of A: 139
Sum of A along axis 0: [34 29 29 14 33]
Sum of A along axis 1: [23 26 34 33 23]
div int [[3 0 2 2 4]
 [2 3 1 2 4]
 [3 4 4 1 3]
 [4 4 4 1 3]
 [4 2 2 0 2]]
A+B=[[12  2  7  8 17]
 [ 6 10  7  9 16]
 [ 8 11 10  7 15]
 [12 11 17  5  7]
 [10 10 10  7 11]]
A-B=[[ 0  0  1  0 -1]
 [ 2  2 -1  1  0]
 [ 6  7  8 -3 -1]
 [ 4  5  1 -1  5]
 [ 8  0 -2 -5 -3]]
Minimum of A: 1
Maximum of A: 9
Minimum of A along axis 0: [4 1 3 1 4]
Maximum of A along axis 1: [8 8 9 9 9]
Exponential of A: [[4.03428793e+02 2.71828183e+00 5.45981500e+01 5.45981500e+01
  2.98095799e+03]
 [5.45981500e+01 4.03428793e+02 2.00855369e+01 1.48413159e+02
  2.98095799e+03]
 [1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00
  1.09663316e+03]
 [2.98095799e+03 2.98095799e+03 8.10308393e+03 7.38905610e+00
  4.03428793e+02]
 [8.10308393e+03 1.48413159e+02 5.45981500e+01 2.71828183e+00


In [9]:
# ============================================================
# Statistical Operations
# ============================================================
print(f'Mean of A: {A.mean()}')
print(f'Standard deviation of A: {A.std()}') # standard deviation
print(f'Variance of A: {A.var()}') # variance
print(f'Correlation of A: {np.corrcoef(A)}')
values, count=np.unique(A, return_counts=True) # unique values with counts
print(f'valeurs uniques de A: {values}')
print(f'fréquences de A: {count}')
values[count.argsort()] # most frequent value
print(f'valeur la plus fréquente de A: {values}')

Mean of A: 5.56
Standard deviation of A: 2.546841180757057
Variance of A: 6.486400000000001
Correlation of A: [[ 1.          0.31898089 -0.18078916 -0.13044332  0.17304133]
 [ 0.31898089  1.         -0.08169674 -0.30713958 -0.20751903]
 [-0.18078916 -0.08169674  1.          0.95654897  0.53334313]
 [-0.13044332 -0.30713958  0.95654897  1.          0.68977371]
 [ 0.17304133 -0.20751903  0.53334313  0.68977371  1.        ]]
valeurs uniques de A: [1 2 3 4 5 6 7 8 9]
fréquences de A: [2 2 1 5 2 3 2 4 4]
valeur la plus fréquente de A: [1 2 3 4 5 6 7 8 9]


In [12]:
# ============================================================
# Algebre lineaire
# ============================================================

A=np.ones((2, 3))
B=np.ones((3, 2))
print(A)
print(B)
print(f'Transpose of A: {A.T}')
print(f'Product of A and B: {A.dot(B)}') # produit matriciel






[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Transpose of A: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Product of A and B: [[3. 3.]
 [3. 3.]]


In [29]:
A=np.random.randint(1, 10, (3, 3))
print(A)
print(f'determinant of an array: {np.linalg.det(A)}') # determinant

print(f'Inverse of a matrix: {np.linalg.inv(A)}') # inverse
print(f'pseudo-inverse of a matrix: {np.linalg.pinv(A)}')
print(f'Compute the eigenvalues: {np.linalg.eig(A)}') # valeurs et vecteurs propres

[[7 2 3]
 [5 2 4]
 [3 5 8]]
determinant of an array: -27.0
Inverse of a matrix: [[ 0.14814815  0.03703704 -0.07407407]
 [ 1.03703704 -1.74074074  0.48148148]
 [-0.7037037   1.07407407 -0.14814815]]
pseudo-inverse of a matrix: [[ 0.14814815  0.03703704 -0.07407407]
 [ 1.03703704 -1.74074074  0.48148148]
 [-0.7037037   1.07407407 -0.14814815]]
Compute the eigenvalues: EigResult(eigenvalues=array([13.3190063 +0.j,  4.16742764+0.j, -0.48643394+0.j]), eigenvectors=array([[-0.49557556+0.j, -0.6590156 +0.j,  0.03132825+0.j],
       [-0.47572049+0.j, -0.16675971+0.j, -0.8659614 +0.j],
       [-0.72670137+0.j,  0.7334096 +0.j,  0.49912864+0.j]]))


In [32]:

C=np.random.randn(5,5)
C[0,2]=np.nan
C[4,3]=np.nan
print(C)
print(f'mean with nan :{np.nanmean(C)}')
print(f'mask of nan in the matrix:{np.isnan(C)}')
print (f'precentage of nan sum in the dataset:{np.isnan(C).sum()/C.size}')
print(C)
C[np.isnan(C)]=0
print(f'Remplace the nan per 0 :{C}')

[[ 0.46693969 -1.3402814          nan  0.99379727 -0.61651086]
 [ 0.20493776 -0.47954552  1.51238621 -1.34683907 -2.78073771]
 [-0.0894738   0.55814156  0.75572522  0.47821507 -0.05390584]
 [-1.24190139 -1.65849531 -0.35337169  1.6565077   1.51191283]
 [-0.90680429 -0.77721733 -0.73922809         nan -0.02647272]]
mean with nan :-0.1857487698368161
mask of nan in the matrix:[[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]]
precentage of nan sum in the dataset:0.08
[[ 0.46693969 -1.3402814          nan  0.99379727 -0.61651086]
 [ 0.20493776 -0.47954552  1.51238621 -1.34683907 -2.78073771]
 [-0.0894738   0.55814156  0.75572522  0.47821507 -0.05390584]
 [-1.24190139 -1.65849531 -0.35337169  1.6565077   1.51191283]
 [-0.90680429 -0.77721733 -0.73922809         nan -0.02647272]]
Remplace the nan per 0 :[[ 0.46693969 -1.3402814   0.          0.99379727 -0.61651086]
 [ 0.2049377