In [17]:



import random
import math
import numpy as np
import statistics
import os
import glob

liste = random.sample(range(100), 10)
print("Liste aléatoire :", liste)

liste_str=['java', 'python', 'c++', 'c#', 'javascript']

Liste aléatoire : [45, 52, 94, 8, 64, 80, 5, 48, 63, 85]


In [8]:
# ============================================================
# MATH
# ============================================================

print(math.cos(2 * math.pi))
print(math.exp(5))

1.0
148.4131591025766


In [ ]:
# ============================================================
# STATISTICS
# ============================================================

print(statistics.mean(liste))
print(statistics.variance(liste))




47
877.1111111111111


In [47]:
# ============================================================
# RANDOM
# ========================================================
print(random.randint(1, 100))
print(random.choice(liste))
print(random.choice(liste_str))
print(random.sample(liste, 3))
print(random.sample(liste_str, 3))
print("Liste mélangée :", liste)
#random.seed(0)
print(random.choice(liste_str))

print(random.random())       # float
print(random.randint(5, 10)) # int
print(random.randrange(100)) # int entre 0 et 100

# générer une liste aléatoire
print(random.sample(range(100), random.randrange(10)))

46
48
javascript
[94, 8, 45]
['python', 'javascript', 'c#']
Liste mélangée : [45, 52, 94, 8, 64, 80, 5, 48, 63, 85]
javascript
0.25068733928511167
9
56
[1, 60]


In [48]:
# ============================================================
# OS
# ========================================================
print(os.getcwd())

c:\Users\SECK TOURE\Documents\Code-multilanguage\python\neurone\notebooks


In [49]:
# ============================================================
# glob
# ========================================================
glob.glob('*') 
glob.glob("*.ipynb")

['main.ipynb',
 'neurone_arificielle.ipynb',
 'PYTHON_CONDITIONS.ipynb',
 'PYTHON_DICO.ipynb',
 'PYTHON_LISTE_COMPREHENSION.ipynb',
 'PYTHON_PACKAGE_MODULE.ipynb',
 'PYTHON_TUPLES_LISTES.ipynb',
 'PYTHON_VARIABLES_ET_FONCTIONS.ipynb']

In [8]:
# ============================================================
# Standardiser la matrice  A sur chaque colonne 
# Chaque colonne doit avoir :
# - Une moyenne 0
# - un ecart type de 1
# ========================================================
import random
import numpy as np


np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
print(A)
D = (A- A.mean(axis=0))/A.std(axis=0)
print(f'Standardisation de A par colonne: {D}')
print(f'La moyenne est null ou proche de zero:{D.mean(axis=0)}')
print(f'L ecart typede chaque colonne est de 1{D.std(axis=0)}')


[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]
 [ 9 20 80 69 79]
 [47 64 82 99 88]
 [49 29 19 19 14]
 [39 32 65  9 57]
 [32 31 74 23 35]]
Standardisation de A par colonne: [[-0.02206157  0.          0.13173823  0.72539252  0.10755798]
 [-1.56637126  1.61579632 -1.48676006 -0.33034307  0.96802178]
 [ 1.12513992  1.84021247  1.03508612 -1.14768676 -0.27965074]
 [ 0.90452425 -0.35906585  0.99744662  0.0102168   1.01104497]
 [ 1.6104944  -0.44883231 -1.33620208  1.0659524   0.32267393]
 [-1.56637126 -1.21184724  0.73397016  0.7935045   0.62383626]
 [ 0.11030784  0.76301493  0.80924915  1.81518411  1.01104497]
 [ 0.1985541  -0.80789816 -1.56203905 -0.90929485 -2.17267111]
 [-0.24267724 -0.67324847  0.16937773 -1.24985473 -0.32267393]
 [-0.55153918 -0.7181317   0.50813319 -0.77307091 -1.26918412]]
La moyenne est null ou proche de zero:[-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]
L ecart typede chaque colonne est