In [11]:
# ============================================================
# NUMPY BROADCASTING
# ============================================================

import numpy as np

np.random.seed(0)
A = np.random.randint(0, 10, [4, 1])
B = np.ones((4,))
print (f'A={A} Dimension de A:{A.shape}')
print (f'B={B} Dimension de B:{B.shape}')
print (f' With broadcasting A-B={A-B}')
B=B.reshape(B.shape[0], 1)
print (f'B={B} new Dimension of B:{B.shape}')
print (f' With broadcasting A-B={A-B}')


A=[[5]
 [0]
 [3]
 [3]] Dimension de A:(4, 1)
B=[1. 1. 1. 1.] Dimension de B:(4,)
 With broadcasting A-B=[[ 4.  4.  4.  4.]
 [-1. -1. -1. -1.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
B=[[1.]
 [1.]
 [1.]
 [1.]] new Dimension of B:(4, 1)
 With broadcasting A-B=[[ 4.]
 [-1.]
 [ 2.]
 [ 2.]]
