In [15]:
import numpy as np
import random

A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(A) # Afficher le tableau
print(A.ndim) # Nombre de dimensions
print(A.shape) # Forme du tableau
print(A.size) # Nombre total d'éléments
print(A.dtype) # Type des éléments
print(A.itemsize) # Taille en octets d'un élément
print(A.nbytes) # Taille totale en octets
print(A.T)  # Transposée
print(A.flatten())  # Aplatir le tableau
print(A.reshape(1, 9))  # Redimensionner le tableau



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int64
8
72
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


In [121]:
B=np.array([[1, 2, 3], [4, 5, 6]])
print(B)
print(B.ndim)
print(B.shape)
Bbis=np.zeros((2, 3))
print(Bbis)
C=np.ones((5, 12))
print(C)  # Tableau de uns
D=np.eye(3,3)
print(D)  # Matrice identité
E=np.full((7, 3), random.randint(0, 500))  # Tableau rempli de 7
print(E)
F=np.random.randn(3, 4)  # Tableau de nombres aléatoires
print(F)
np.random.seed(2565588)  # Fixer la graine pour la reproductibilité
G=np.random.randn(3, 4)  # Tableau de nombres aléatoires
print(G)
print(np.linspace(0, 10, 5))  # Tableau de nombres aléatoires uniformes
print(np.arange(0, 10, 2))  # Tableau de nombres aléatoires uniformes

[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[72 72 72]
 [72 72 72]
 [72 72 72]
 [72 72 72]
 [72 72 72]
 [72 72 72]
 [72 72 72]]
[[-0.72620249  2.0436994  -0.47532552 -1.97758427]
 [-1.33188368 -1.23900305  0.10043793 -1.73275852]
 [-0.93656198 -0.94536364  1.49477346 -0.14201087]]
[[ 1.11968339  0.59482159 -1.49328403  1.02639736]
 [-0.72105535  0.69127944 -0.75562486  0.02065381]
 [ 0.16165216  0.60302417 -0.83742017  0.64110095]]
[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]


In [129]:
# ============================================================
# MANIPULATION DE TABLEAUX
# =======================================================
A=np.zeros((3, 4))
print(A)
B=np.ones((3, 4))
print(B)

C=np.hstack((A, B))  # Concaténation horizontale
print(C)
print(np.shape(C))  

D=np.vstack((A, B))  # Concaténation verticale
print(D)
print(np.shape(D))

E=np.concatenate((A, B), axis=0)  # Concaténation verticale
print(E)
print(np.shape(E))

H= np.reshape(E, (2, 12))  # Redimensionner le tableau 
print(H)

print(np.ravel(H))  # Afficher la forme du tableau

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]
(3, 8)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(6, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(6, 4)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [128]:
A = np.array([1, 2, 3])
print(A.shape)  # Afficher la forme du tableau

A = A.reshape((A.shape[0], 1))
print(A.shape)

A = A.squeeze()
print(A.shape)

(3,)
(3, 1)
(3,)
