In [9]:
# Importer NumPy pour manipuler les tableaux
import numpy as np

# Importer Matplotlib pour créer des graphiques
import matplotlib.pyplot as plt

# Importer Pandas pour manipuler les DataFrames
import pandas as pd

# Importer Seaborn pour la visualisation des données
import seaborn as sns

# Importer SGDClassifier pour la classification
from sklearn.linear_model import SGDClassifier


# ==================================================
# SimpleImputer
# ==================================================

# Importer SimpleImputer pour remplacer les valeurs manquantes
from sklearn.impute import SimpleImputer


# Créer un tableau NumPy contenant une valeur manquante (NaN)
X = np.array([
    [10, 3],
    [0, 4],
    [5, 3],
    [np.nan, 3]
])

SimpleImputer(missing_values=np.nan, strategy='mean')  # Créer un objet SimpleImputer pour remplacer les valeurs manquantes par la moyenne
inputer = SimpleImputer(missing_values=np.nan, strategy='mean')

inputer.fit_transform(X)  # Ajuster l'imputer aux données et transformer les données

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

In [10]:
X_test = np.array([
    [10, 3],
    [40, 2],
    [5, 5],
    [np.nan, np.nan]
])
inputer.fit_transform(X_test)  # Transformer les nouvelles données en remplaçant les valeurs manquantes par la moyenne calculée à partir des données d'entraînement


array([[10.        ,  3.        ],
       [40.        ,  2.        ],
       [ 5.        ,  5.        ],
       [18.33333333,  3.33333333]])

In [20]:
# ====================================================================================================
# KNNImputer -> pour remplacer les valeurs manquantes par la moyenne des k plus proches voisins
# ====================================================================================================
from sklearn.impute import KNNImputer

# Créer un tableau NumPy contenant une valeur manquante (NaN)
X = np.array([
    [1, 100],
    [2, 30],
    [3, 15],
    [np.nan, 20]
])

KNNImputer(n_neighbors=6)  # Créer un objet KNNImputer pour remplacer les valeurs manquantes par la moyenne des k plus proches voisins
inputer.fit_transform(X)  # Ajuster l'imputer aux données et transformer les données    

array([[  1., 100.],
       [  2.,  30.],
       [  3.,  15.],
       [  2.,  20.]])

In [24]:
# ====================================================================================================
# MissingIndicator -> pour remplacer les valeurs manquantes par la moyenne des k plus proches voisins
# ====================================================================================================
from sklearn.impute import MissingIndicator
from sklearn.pipeline import make_union


# Créer un tableau NumPy contenant une valeur manquante (NaN)
X = np.array([
    [1, 100],
    [2, 30],
    [3, 15],
    [np.nan, np.nan]
])

MissingIndicator().fit_transform(X)

pipeline = make_union(SimpleImputer(strategy='constant', fill_value=-99)
                       ,MissingIndicator())

pipeline.fit_transform(X)

array([[  1., 100.,   0.,   0.],
       [  2.,  30.,   0.,   0.],
       [  3.,  15.,   0.,   0.],
       [-99., -99.,   1.,   1.]])